import { Package, ShoppingBag, Star, Users } from 'lucide-react'
import { catalogProducts, reviews } from '../../data/content.js'
import { formatPrice } from '../../utils/currency.js'

const orders = [{ id: 'JEM-1048', customer: 'Amara Whitfield', total: '₹329.00', status: 'Processing' }, { id: 'JEM-1047', customer: 'Priya Nandakumar', total: '₹1,850.00', status: 'Shipped' }, { id: 'JEM-1046', customer: 'Sofia Marchetti', total: '₹279.00', status: 'Delivered' }]
const customers = [{ name: 'Amara Whitfield', email: 'amara@example.com', orders: 4, spend: '₹1,240' }, { name: 'Priya Nandakumar', email: 'priya@example.com', orders: 3, spend: '₹2,105' }, { name: 'Sofia Marchetti', email: 'sofia@example.com', orders: 2, spend: '₹558' }]
function Title({ children, description }) { return <div className="mb-7"><h1 className="font-display text-3xl text-ink">{children}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div> }
function Table({ headings, children }) { return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headings.map((heading) => <th key={heading} className="px-5 py-4 font-semibold">{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
export function Dashboard() { const cards = [['Revenue', '₹12,480', ShoppingBag], ['Orders', '38', Package], ['Customers', '246', Users], ['Reviews', '4.8 / 5', Star]]; return <><Title description="A live overview of your jewellery business.">Dashboard</Title><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><Icon size={19} className="text-gold" /></div><p className="mt-5 font-display text-3xl text-ink">{value}</p><p className="mt-2 text-xs text-emerald-dark">+12.5% this month</p></div>)}</div><div className="mt-7"><Title description="Most recent purchases.">Recent orders</Title><OrdersTable /></div></> }
function OrdersTable() { return <Table headings={['Order', 'Customer', 'Total', 'Status']}>{orders.map((order) => <tr key={order.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 font-medium text-ink">{order.id}</td><td className="px-5 py-4 text-slate-600">{order.customer}</td><td className="px-5 py-4">{order.total}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald/15 px-2.5 py-1 text-xs font-semibold text-emerald-dark">{order.status}</span></td></tr>)}</Table> }
export function AdminProducts() { return <><Title description={`${catalogProducts.length} products in your catalogue.`}>Products</Title><Table headings={['Product', 'Category', 'Price', 'Status']}>{catalogProducts.map((product) => <tr key={product.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-3"><div className="flex items-center gap-3"><img src={product.images[0]} alt="" className="h-10 w-10 rounded-lg object-cover" /><span className="font-medium text-ink">{product.name}</span></div></td><td className="px-5 py-3 text-slate-600">{product.category}</td><td className="px-5 py-3">{formatPrice(product)}</td><td className="px-5 py-3"><span className="text-xs font-semibold text-emerald-dark">Active</span></td></tr>)}</Table></> }
export function AdminOrders() { return <><Title description="Review and fulfil current customer orders.">Orders</Title><OrdersTable /></> }
export function AdminCustomers() { return <><Title description="Your most recent customer records.">Customers</Title><Table headings={['Customer', 'Orders', 'Lifetime spend']}>{customers.map((customer) => <tr key={customer.email} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-medium text-ink">{customer.name}</p><p className="text-xs text-slate-500">{customer.email}</p></td><td className="px-5 py-4">{customer.orders}</td><td className="px-5 py-4">{customer.spend}</td></tr>)}</Table></> }
export function AdminReviews() { return <><Title description="Recent customer feedback from your storefront.">Reviews</Title><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><img src={review.img} alt="" className="h-10 w-10 rounded-full object-cover" /><div><p className="font-semibold text-ink">{review.name}</p><p className="text-xs text-gold">{'★'.repeat(review.rating)}</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">“{review.text}”</p></article>)}</div></> }
